import { useEffect, useMemo, useState } from 'react'
import { Area, Bar, BarChart, CartesianGrid, ComposedChart, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { getMetrics, getSeries } from '../api/client'
import type { Metrics, Mode } from '../api/types'
import { EmptyState, ErrorState, Metric, Panel, number, percent } from '../components/Shared'

type SeriesRow = { target_time: string; p10: number; p50: number; p90: number; actual: number | null }
const names: Record<string, string> = { hybrid: 'Hybrid', mos_pc: 'MOS + curve', raw_pc: 'Raw NWP + curve', climatology: 'Climatology', persistence: 'Persistence' }

export function BacktestPage() {
  const [mode, setMode] = useState<Exclude<Mode, 'test'>>('val_feb2025')
  const [metrics, setMetrics] = useState<Metrics | null>(null)
  const [series, setSeries] = useState<SeriesRow[]>([])
  const [error, setError] = useState('')
  const [week, setWeek] = useState(0)
  useEffect(() => {
    let active = true
    setError('')
    Promise.all([getMetrics(mode), getSeries(mode)]).then(([result, values]) => { if (active) { setMetrics(result); setSeries(values.rows); setWeek(0) } }).catch(cause => { if (active) setError(cause.message) })
    return () => { active = false }
  }, [mode])
  const chartSeries = useMemo(() => series.slice(week * 168, (week + 1) * 168).map((row, index) => ({ ...row, hour: index, band: [row.p10 * 100, row.p90 * 100], p50pct: row.p50 * 100, actualPct: row.actual == null ? null : row.actual * 100 })), [series, week])
  const modelBars = metrics ? Object.entries(metrics.models).map(([name, value]) => ({ name: names[name] || name, nmae: +(value.nmae * 100).toFixed(1), fill: name === 'hybrid' ? '#2dd4bf' : '#68829f' })) : []
  const lead = metrics?.mae_by_lead.map(row => ({ ...row, hybrid: row.hybrid * 100, persistence: row.persistence * 100, raw_pc: row.raw_pc * 100 })) || []
  const reliability = metrics?.reliability.map(row => ({ nominal: row.nominal * 100, observed: row.observed * 100 })) || []

  return <div className="page-stack"><div className="page-intro"><div><h1>Backtest & skill</h1><p>Replay the same issue procedure on historical periods where measured output is available.</p></div><label className="select-label">Validation period<select value={mode} onChange={event => setMode(event.target.value as Exclude<Mode, 'test'>)}><option value="val_feb2025">February 2025 · seasonal twin</option><option value="val_winter">Winter 2025–26</option></select></label></div>
    {error ? <ErrorState message={error} /> : null}
    {metrics ? <><div className="validation-note">Validation only · Test period February 2026 actual generation is unavailable. No hidden-test accuracy is claimed.</div><div className="metric-grid metric-grid-four"><Metric label="Day-ahead NMAE" value={percent(metrics.models.hybrid.nmae, 1)} detail={`${metrics.n_hours} evaluated hours`} tone="teal" /><Metric label="Skill vs persistence" value={percent(metrics.models.hybrid.skill_vs_persistence, 1)} detail="Relative improvement" /><Metric label="P10–P90 coverage" value={metrics.models.hybrid.picp_80 == null ? '—' : percent(metrics.models.hybrid.picp_80, 1)} detail="Target: 80%" /><Metric label="Training cutoff" value={metrics.train_end.slice(0, 10)} detail="No later data in training" /></div>
      <div className="analysis-grid"><Panel title="Model comparison" caption="Lower day-ahead normalized mean absolute error is better"><ResponsiveContainer width="100%" height={260}><BarChart data={modelBars} layout="vertical" margin={{ top: 8, right: 18, left: 24, bottom: 4 }}><CartesianGrid stroke="#23344c" strokeDasharray="3 5" horizontal={false} /><XAxis type="number" tickFormatter={value => `${value}%`} stroke="#8fa3bf" tick={{ fontSize: 11 }} /><YAxis type="category" dataKey="name" stroke="#8fa3bf" width={110} tick={{ fontSize: 11 }} /><Tooltip formatter={value => `${value}% NMAE`} contentStyle={{ background: '#111a2e', border: '1px solid #1e2a44' }} /><Bar dataKey="nmae" fill="#2dd4bf" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></Panel><Panel title="Error by forecast lead" caption="Shows where the hybrid forecast outperforms persistence"><ResponsiveContainer width="100%" height={260}><LineChart data={lead} margin={{ top: 8, right: 18, left: 4, bottom: 4 }}><CartesianGrid stroke="#23344c" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="lead_h" stroke="#8fa3bf" tick={{ fontSize: 11 }} interval={7} /><YAxis stroke="#8fa3bf" tick={{ fontSize: 11 }} tickFormatter={value => `${value}%`} /><Tooltip formatter={value => `${number(Number(value), 1)}% MAE`} contentStyle={{ background: '#111a2e', border: '1px solid #1e2a44' }} /><Line dataKey="hybrid" name="Hybrid" stroke="#2dd4bf" strokeWidth={2} dot={false} /><Line dataKey="persistence" name="Persistence" stroke="#f59e0b" strokeWidth={2} dot={false} /><ReferenceLine x={24} stroke="#a1afc2" strokeDasharray="4 4" /></LineChart></ResponsiveContainer></Panel></div>
      <div className="analysis-grid"><Panel title="Interval reliability" caption="Observed coverage should stay near the nominal diagonal"><ResponsiveContainer width="100%" height={230}><LineChart data={reliability} margin={{ top: 8, right: 16, left: 4, bottom: 4 }}><CartesianGrid stroke="#23344c" strokeDasharray="3 5" /><XAxis dataKey="nominal" stroke="#8fa3bf" tickFormatter={value => `${value}%`} tick={{ fontSize: 11 }} /><YAxis domain={[0, 100]} stroke="#8fa3bf" tickFormatter={value => `${value}%`} tick={{ fontSize: 11 }} /><Tooltip formatter={value => `${value}%`} contentStyle={{ background: '#111a2e', border: '1px solid #1e2a44' }} /><Line dataKey="nominal" name="Ideal" stroke="#68829f" strokeDasharray="4 4" dot={false} /><Line dataKey="observed" name="Observed" stroke="#38bdf8" strokeWidth={2} /></LineChart></ResponsiveContainer></Panel><Panel title="Daily error" caption="Day-by-day hybrid and persistence error"><div className="daily-grid">{metrics.daily.map(day => <div key={day.date} className="daily-cell" title={`${day.date} · hybrid ${percent(day.hybrid, 1)} · persistence ${percent(day.persistence, 1)}`} style={{ background: `rgba(45, 212, 191, ${Math.max(0.12, 0.8 - day.hybrid * 2.4)})` }}><small>{day.date.slice(8)}</small><strong>{percent(day.hybrid, 0)}</strong></div>)}</div></Panel></div>
      <Panel title="Observed vs forecast" caption="Hourly normalized farm power (% of assumed installed capacity): measured output and prediction interval" action={<label className="select-label compact">Week<select value={week} onChange={event => setWeek(Number(event.target.value))}>{Array.from({ length: Math.max(1, Math.ceil(series.length / 168)) }, (_, index) => <option value={index} key={index}>Week {index + 1}</option>)}</select></label>}>{series.length ? <ResponsiveContainer width="100%" height={260}><ComposedChart data={chartSeries} margin={{ top: 8, right: 18, left: 4, bottom: 4 }}><CartesianGrid stroke="#23344c" strokeDasharray="3 5" vertical={false} /><XAxis dataKey="hour" stroke="#8fa3bf" tick={{ fontSize: 11 }} interval={23} /><YAxis domain={[0, 100]} stroke="#8fa3bf" tick={{ fontSize: 11 }} tickFormatter={value => `${value}%`} /><Tooltip formatter={value => `${number(Number(value), 1)}%`} contentStyle={{ background: '#111a2e', border: '1px solid #1e2a44' }} /><Area dataKey="band" name="P10–P90" fill="#38bdf8" fillOpacity={0.2} stroke="none" /><Line dataKey="p50pct" name="P50" stroke="#38bdf8" strokeWidth={2} dot={false} /><Line dataKey="actualPct" name="Actual" stroke="#f8fafc" strokeWidth={1.5} dot={false} /></ComposedChart></ResponsiveContainer> : <EmptyState message="Measured series is not available for this validation period." />}</Panel>
    </> : !error ? <div className="loading">Loading historical evaluation…</div> : null}
  </div>
}
